In [2]:
!pip install --upgrade xlrd

Requirement already satisfied: xlrd in c:\users\miche\anaconda3\lib\site-packages (2.0.1)

In [3]:
import pandas as pd
df = pd.read_excel('cars.xls')
df.head()

,Price,Mileage,Make,Model,Trim,Type,Cylinder,Liter,Doors,Cruise,Sound,Leather
0,17314.103129,8221,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,1
1,17542.036083,9135,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0
2,16218.847862,13196,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0
3,16336.913140,16342,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,0,0
4,16339.170324,19832,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,0,1

In [ ]:
"""
StandaedScalar : I t transforms the data in such a manner that it has mean as 0
and standard deviation 1. in short it standardizes the data. Standardization is useful for data which has negative values.
It arranges the data in Standard normal distribution.
It is more useful in classification than regression.

Normalizer : It squeezes the data between 0 and 1.
It performs normalization.
Due to decreased range and magnitude, the gradients in the training
process do not explode and you do not get higher values of loss.
Is more useful in regression than classification.
"""
"""
We can use pandas to spilt this matrix intothe feature vectors we're interested in and the value we're trying to predict.
Note how we are avoiding the make and model; regressions dont work well with with ordinal values, unless you can convert them 
into some numerical order that makes sense somehow.
Lets scale our feature data into sdame range so we can easily compare the coefficients w eend up with."""

In [7]:
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
#this is our variable for multivariate regression..
x = df[["Mileage", "Cylinder", "Doors"]].values
#this is our model...
y = df["Price"]
#matrix..
#creation..
#output..
#x[["Mileage", "Cylinder","Doors"]] = scale.fit_transform(x[["Mileage","Cylinder", "Doors"]].as_matrix())
#"Doors"]].as_matrix())
print(x)

[[ 8221     6     4]
 [ 9135     6     4]
 [13196     6     4]
 ...
 [20484     6     4]
 [25979     6     4]
 [35662     6     4]]

In [8]:
import statsmodels.api as  sm
df["Model_ord"] = pd.Categorical(df.Model).codes
df

,Price,Mileage,Make,Model,Trim,Type,Cylinder,Liter,Doors,Cruise,Sound,Leather,Model_ord
0,17314.103129,8221,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,1,10
1,17542.036083,9135,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0,10
2,16218.847862,13196,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0,10
3,16336.913140,16342,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,0,0,10
4,16339.170324,19832,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,0,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,16507.070267,16229,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,0,0,21
800,16175.957604,19095,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,0,21
801,15731.132897,20484,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,0,21
802,15118.893228,25979,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,0,21
803,13585.636802,35662,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,0,0,21

In [13]:
# r import statsmodels.api as sm 
# create a model that predict the price of my car bbased on Mileage,
# Modelord and door..
# then convert model categorical data into numerical value..
# I am converting text to numerical value using Categorical() method..
#Input value of x axis Mileage, Model_Ord, Doors predict the value for 
# y  axis
# value price
import statsmodels.api as sm
df["Model_ord"] = pd.Categorical(df.Model).codes
x = df[["Mileage","Model_ord", "Doors"]]
y = df["Price"]
#print(x)
#create my model here...
#ordinal least square using OLS() fit my columns square x and y
# Adding key()/ same constant to all fields..using add_constant(x)
x1 = sm.add_constant(x)
#print(x1)
est = sm.OLS(y, x1).fit()
est.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.042
Model:                            OLS   Adj. R-squared:                  0.038
Method:                 Least Squares   F-statistic:                     11.57
Date:                Tue, 02 Jan 2024   Prob (F-statistic):           1.98e-07
Time:                        13:45:11   Log-Likelihood:                -8519.1
No. Observations:                 804   AIC:                         1.705e+04
Df Residuals:                     800   BIC:                         1.706e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.125e+04   1809.549     17.272      0.000    2.77e+04    3.48e+04
Mileage       -0.1765      0.042     -4.227      0.000      -0.259      -0.095
Model_ord    -39.0387     39.326     -0.993      0.321    -116.234      38.157
Doors      -1652.9303    402.649     -4.105      0.000   -2443.303    -862.558
==============================================================================
Omnibus:                      206.410   Durbin-Watson:                   0.080
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              470.872
Skew:                           1.379   Prob(JB):                    5.64e-103
Kurtosis:                       5.541   Cond. No.                     1.15e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.15e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
More doors does not mean a higher price (maybe it implies a sport car in some cases)So its 
not surprising that its pretty useless as predictor here. This is very small data set however ,
so we cant read much meaning into it.